Backport phonon build fix from 4.9 branch
We import this:
https://github.com/KDE/phonon/commit/543183aa844a27869c7fc46957ff097c155d6575

Into the 4.9.0 commit in order to fix the build, because otherwise we get this build failure in
phonen:

In file included from /run/build-runtime/phonon/phonon/audiooutput_p.h:28:0,
                 from /run/build-runtime/phonon/phonon/audiooutput.cpp:23:
/run/build-runtime/phonon/phonon/phononconfig_p.h:6:30: fatal error: QtCore/qfeatures.h: No such file or directory
 #include <QtCore/qfeatures.h>
                              ^
compilation terminated.